server:
  port: 8888
spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
#      name: application-dev
      server:
        git:
          uri: https://github.com/ShantanuKumarSinha/config-server
          clone-on-start: true


